<<<<<<< HEAD
# Generated by Django 4.1.6 on 2023-02-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
=======
# Generated by Django 4.1.6 on 2023-02-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
>>>>>>> 55b03087149b060a03fb91d3d02364719933cb76
