# Generated by Django 4.1.6 on 2023-02-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category_listing_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
