# Generated by Django 4.1.6 on 2023-02-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_comment_date_posted_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='price',
        ),
    ]
