# Generated by Django 4.1.6 on 2023-02-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_status_listing_acitve_listing_display_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='acitve',
            new_name='active',
        ),
    ]
