# Generated by Django 4.1.6 on 2023-02-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_acitve_listing_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='display_price',
            new_name='current_price',
        ),
    ]
