# Generated by Django 4.1.6 on 2023-02-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_rename_display_price_listing_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starter_price',
            field=models.PositiveIntegerField(),
        ),
    ]
